# Generated by Django 4.1 on 2023-08-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
