# Generated by Django 4.2.1 on 2023-05-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progression',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
