# Generated by Django 4.1 on 2023-08-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_progression_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progression',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
