# Generated by Django 4.2.1 on 2023-05-18 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_progression_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progression',
            options={'ordering': ['created_at']},
        ),
    ]
