# Generated by Django 4.2.1 on 2023-05-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_progression_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progression',
            options={'ordering': ['created_at', 'weight']},
        ),
    ]
