# Generated by Django 4.1 on 2023-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_muscle_exercise_created_at_exercise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], max_length=20),
        ),
    ]
