# Generated by Django 4.1 on 2023-08-30 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_progression_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progression",
            options={"ordering": ["-created_at", "-weight"]},
        ),
    ]
