# Generated by Django 4.1 on 2023-08-30 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_progression_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progression",
            options={"ordering": ["-created_at"]},
        ),
    ]
