# Generated by Django 4.1 on 2023-10-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_routine_routineexercise_routineexerciseexecution"),
        ("core", "0010_alter_progression_options"),
    ]

    operations = []
