---
# See https://pre-commit.com for more information
exclude: "central/settings.py"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/akaihola/darker
    rev: 1.7.1
    hooks:
      - id: darker
        args: [--isort]
        additional_dependencies:
          - black~=21.8b0
          - isort~=5.9
  - repo: https://github.com/dhruvmanila/remove-print-statements
    rev: v0.5.1
    hooks:
      - id: remove-print-statements
        args: ["--verbose"] # Show all the print statements to be removed
  - repo: https://github.com/hadialqattan/pycln
    rev: v0.0.1-beta.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
