# Generated by Django 4.1 on 2023-08-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrient",
            name="carbohydrates",
            field=models.FloatField(null=True),
        ),
    ]
