# Generated by Django 4.1 on 2023-08-14 20:15

from django.db import migrations, models


def fix_initial_data(apps, schema_editor):
    Category = apps.get_model("nutrition", "Category")
    Food = apps.get_model("nutrition", "Food")

    import json

    Food.objects.all().delete()

    with open("gym_weight_tracker/nutrition/migrations/taco.json") as json_data:
        data = json.load(json_data)

        for item in data["data"]:
            category, _ = Category.objects.get_or_create(
                id=item["category"]["id"], defaults={"name": item["category"]["name"]}
            )
            Food.objects.get_or_create(
                id=item["id"],
                kcal=item["nutrients"]["kcal"],
                kJ=item["nutrients"]["kJ"],
                protein=item["nutrients"]["protein"],
                carbohydrates=item["nutrients"]["carbohydrates"],
                defaults={"name": item["name"], "category": category},
            )


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0004_insert_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="carbohydrates",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="kJ",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="kcal",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="protein",
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name="Nutrient",
        ),
        migrations.RunPython(fix_initial_data),
    ]
