// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	SelectUm(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
