// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: test.sql

package sqlc

import (
	"context"
)

const selectUm = `-- name: SelectUm :one
SELECT 1
`

func (q *Queries) SelectUm(ctx context.Context) (int32, error) {
	row := q.queryRow(ctx, q.selectUmStmt, selectUm)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
